"""add villages carbon and users

Revision ID: b2c2e80b9fe8
Revises: d583d84febd1
Create Date: 2026-10-05 06:48:34.270529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = 'b2c2e80b9fe8'
down_revision: Union[str, Sequence[str], None] = 'd583d84febd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emission_factors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('emission_factor', sa.String(length=128), nullable=False),
    sa.Column('source', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('villages',
    sa.Column('vlcode', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('subdistrict_code', sa.String(length=16), nullable=True),
    sa.Column('population_2011', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('vlcode')
    )
    op.create_index(op.f('ix_villages_name'), 'villages', ['name'], unique=False)
    op.create_index(op.f('ix_villages_subdistrict_code'), 'villages', ['subdistrict_code'], unique=False)
    op.create_table('activity_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vlcode', sa.String(length=16), nullable=False),
    sa.Column('activity', sa.String(length=128), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['vlcode'], ['villages.vlcode'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vlcode', 'activity')
    )
    op.create_index(op.f('ix_activity_records_vlcode'), 'activity_records', ['vlcode'], unique=False)
    op.create_table('carbon_budgets',
    sa.Column('vlcode', sa.String(length=16), nullable=False),
    sa.Column('total_emission_before', sa.Float(), nullable=True),
    sa.Column('total_sequestration_before', sa.Float(), nullable=True),
    sa.Column('net_emission_before', sa.Float(), nullable=True),
    sa.Column('monthly_net_emission_before', sa.Float(), nullable=True),
    sa.Column('per_capita_emission_before', sa.Float(), nullable=True),
    sa.Column('previous_net_emission', sa.Float(), nullable=True),
    sa.Column('net_emission_after', sa.Float(), nullable=True),
    sa.Column('emission_reduction', sa.Float(), nullable=True),
    sa.Column('sequestration_increase', sa.Float(), nullable=True),
    sa.Column('total_impact', sa.Float(), nullable=True),
    sa.Column('reduction_pct', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['vlcode'], ['villages.vlcode'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('vlcode')
    )
    op.create_table('emission_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vlcode', sa.String(length=16), nullable=False),
    sa.Column('sector', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=128), nullable=False),
    sa.Column('emission_kg', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['vlcode'], ['villages.vlcode'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vlcode', 'sector', 'source')
    )
    op.create_index(op.f('ix_emission_sources_vlcode'), 'emission_sources', ['vlcode'], unique=False)
    op.create_table('interventions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vlcode', sa.String(length=16), nullable=False),
    sa.Column('sector', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('reduction_kg', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['vlcode'], ['villages.vlcode'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vlcode', 'name')
    )
    op.create_index(op.f('ix_interventions_vlcode'), 'interventions', ['vlcode'], unique=False)
    op.create_table('scenario_projections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vlcode', sa.String(length=16), nullable=False),
    sa.Column('scenario', sa.String(length=16), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('emission_kg', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['vlcode'], ['villages.vlcode'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vlcode', 'scenario', 'year')
    )
    op.create_index(op.f('ix_scenario_projections_vlcode'), 'scenario_projections', ['vlcode'], unique=False)
    op.create_table('sequestration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vlcode', sa.String(length=16), nullable=False),
    sa.Column('phase', sa.String(length=16), nullable=False),
    sa.Column('measure', sa.String(length=128), nullable=False),
    sa.Column('area_ha', sa.Float(), nullable=True),
    sa.Column('co2_kg', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['vlcode'], ['villages.vlcode'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vlcode', 'phase', 'measure')
    )
    op.create_index(op.f('ix_sequestration_vlcode'), 'sequestration', ['vlcode'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sequestration_vlcode'), table_name='sequestration')
    op.drop_table('sequestration')
    op.drop_index(op.f('ix_scenario_projections_vlcode'), table_name='scenario_projections')
    op.drop_table('scenario_projections')
    op.drop_index(op.f('ix_interventions_vlcode'), table_name='interventions')
    op.drop_table('interventions')
    op.drop_index(op.f('ix_emission_sources_vlcode'), table_name='emission_sources')
    op.drop_table('emission_sources')
    op.drop_table('carbon_budgets')
    op.drop_index(op.f('ix_activity_records_vlcode'), table_name='activity_records')
    op.drop_table('activity_records')
    op.drop_index(op.f('ix_villages_subdistrict_code'), table_name='villages')
    op.drop_index(op.f('ix_villages_name'), table_name='villages')
    op.drop_table('villages')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_table('emission_factors')
    # ### end Alembic commands ###
